import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Activity, AlertTriangle, CalendarDays, Droplets, Edit3, HeartPulse, MapPin, Phone, Pill, UserRound } from 'lucide-react';
import { Badge, Button, Card, EmptyState, Modal, Spinner } from '../components/UI';
import PatientForm from '../components/PatientForm';
import { getStudent } from '../services/emr';
import { ageFromBirthDate, formatDate, formatDateTime } from '../utils/format';
import { useAuth } from '../context/AuthContext';

export default function PatientProfilePage(){const {id}=useParams();const navigate=useNavigate();const {hasPermission}=useAuth();const [state,setState]=useState({loading:true,data:null,error:''});const [edit,setEdit]=useState(false);const load=()=>getStudent(id).then(data=>setState({loading:false,data,error:''})).catch(e=>setState({loading:false,data:null,error:e.message}));useEffect(load,[id]);if(state.loading)return <Spinner label="Loading complete patient record…"/>;if(!state.data)return <EmptyState title="Patient record unavailable" description={state.error}/>;const p=state.data;const medical=p.medical||{};const guardian=p.guardian||{};return <div className="space-y-6"><Card className="overflow-hidden"><div className="h-28 bg-gradient-to-r from-primary-600 via-cyan-500 to-clinic-teal"/><div className="relative px-5 pb-5 sm:px-7"><div className="-mt-12 flex flex-wrap items-end justify-between gap-4"><div className="flex items-end gap-4"><div className="grid h-24 w-24 place-items-center rounded-3xl border-4 border-white bg-primary-100 text-primary-600 shadow-xl dark:border-slate-900 dark:bg-primary-950"><UserRound className="h-11 w-11"/></div><div className="pb-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-extrabold">{p.full_name}</h2>{medical.medical_alerts&&<Badge tone="red"><AlertTriangle className="mr-1 h-3 w-3"/>Medical Alert</Badge>}</div><p className="mt-1 text-sm text-slate-500">{p.student_id} · {p.grade_level} / {p.section} · {ageFromBirthDate(p.birth_date)} years old</p></div></div><div className="flex gap-2">{hasPermission('visits.create')&&<Button variant="success" onClick={()=>navigate(`/visits/new?student=${p.id}`)}><HeartPulse className="h-4 w-4"/>Register Visit</Button>}{hasPermission('patients.update')&&<Button variant="secondary" onClick={()=>setEdit(true)}><Edit3 className="h-4 w-4"/>Edit</Button>}</div></div></div></Card>
  {medical.medical_alerts&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-red-800 dark:border-red-900 dark:bg-red-950/30 dark:text-red-200"><div className="flex gap-3"><AlertTriangle className="h-5 w-5 shrink-0"/><div><p className="font-bold">Important medical alert</p><p className="mt-1 text-sm">{medical.medical_alerts}</p></div></div></div>}
  <div className="grid gap-6 xl:grid-cols-3"><div className="space-y-6 xl:col-span-2"><Card className="p-5"><h3 className="mb-4 font-bold">Basic information</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[['Birth Date',formatDate(p.birth_date),CalendarDays],['Sex',p.sex,UserRound],['Contact',p.contact_number||'—',Phone],['Address',p.address||'—',MapPin],['Blood Type',medical.blood_type||'Unknown',Droplets],['Status',p.status,Activity]].map(([label,value,Icon])=><div key={label} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800/50"><div className="flex items-center gap-2 text-xs font-semibold text-slate-500"><Icon className="h-4 w-4"/>{label}</div><p className="mt-1 text-sm font-bold">{value}</p></div>)}</div></Card><Card className="p-5"><h3 className="mb-4 font-bold">Medical information</h3><dl className="grid gap-4 sm:grid-cols-2"><div><dt className="text-xs font-bold uppercase text-slate-500">Allergies</dt><dd className="mt-1 text-sm">{medical.allergies||'None recorded'}</dd></div><div><dt className="text-xs font-bold uppercase text-slate-500">Existing Conditions</dt><dd className="mt-1 text-sm">{medical.existing_conditions||'None recorded'}</dd></div><div><dt className="text-xs font-bold uppercase text-slate-500">Current Medications</dt><dd className="mt-1 text-sm">{medical.current_medications||'None recorded'}</dd></div><div><dt className="text-xs font-bold uppercase text-slate-500">Immunization</dt><dd className="mt-1 text-sm">{medical.immunization_information||'Not recorded'}</dd></div><div className="sm:col-span-2"><dt className="text-xs font-bold uppercase text-slate-500">Medical History</dt><dd className="mt-1 whitespace-pre-wrap text-sm">{medical.medical_history||'No history recorded'}</dd></div></dl></Card><Card className="p-5"><h3 className="mb-5 font-bold">Medical timeline</h3>{p.visits.length?<div className="relative ml-3 border-l-2 border-primary-200 pl-7 dark:border-primary-900">{p.visits.map((visit,i)=><button key={visit.id} onClick={()=>navigate(`/visits/${visit.id}`)} className="relative mb-6 block w-full text-left last:mb-0"><span className="absolute -left-[36px] top-1 grid h-4 w-4 place-items-center rounded-full bg-primary-500 ring-4 ring-white dark:ring-slate-900"/><p className="text-xs font-bold text-primary-600">{formatDate(visit.visit_date)} · {visit.visit_type}</p><p className="mt-1 font-bold">{visit.complaint||visit.reason_for_visit}</p><p className="mt-1 text-sm text-slate-500">{visit.diagnosis||'Consultation not yet completed'}</p></button>)}</div>:<EmptyState title="No clinic visits recorded"/>}</Card></div>
  <div className="space-y-6"><Card className="p-5"><h3 className="mb-4 font-bold">Visit summary</h3><div className="space-y-3">{[['Total visits',p.total_visits||0],['Last visit',formatDate(p.last_visit)],['Common complaint',p.most_common_complaint||'—'],['Last consultation',formatDateTime(p.last_consultation)],['Recent medicine',p.issuances[0]?.medicine_summary||'—']].map(([label,value])=><div key={label} className="flex items-start justify-between gap-3 border-b border-slate-100 pb-3 last:border-0 dark:border-slate-800"><span className="text-sm text-slate-500">{label}</span><strong className="max-w-[55%] text-right text-sm">{value}</strong></div>)}</div></Card><Card className="p-5"><h3 className="mb-4 font-bold">Emergency contact</h3>{guardian.full_name?<div className="space-y-2 text-sm"><p className="font-bold">{guardian.full_name}</p><p className="text-slate-500">{guardian.relationship}</p><p className="flex items-center gap-2"><Phone className="h-4 w-4 text-primary-500"/>{guardian.contact_number||'No number'}</p><p className="text-slate-500">{guardian.email}</p></div>:<EmptyState title="No guardian recorded"/>}</Card><Card className="p-5"><h3 className="mb-4 font-bold">Recent medicines issued</h3>{p.issuances.length?<div className="space-y-3">{p.issuances.slice(0,5).map(row=><div key={row.id} className="flex gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-800/50"><Pill className="h-5 w-5 shrink-0 text-primary-500"/><div><p className="text-sm font-bold">{row.medicine_summary}</p><p className="text-xs text-slate-500">{formatDateTime(row.issued_at)}</p></div></div>)}</div>:<p className="text-sm text-slate-500">No medicines issued.</p>}</Card></div></div>
  <Modal open={edit} onClose={()=>setEdit(false)} title="Edit Patient" size="full"><PatientForm patient={p} onCancel={()=>setEdit(false)} onSaved={()=>{setEdit(false);load();}}/></Modal></div>;}
