import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowUpDown, Eye, Pencil, Plus, UserRound } from 'lucide-react';
import { Badge, Button, Card, EmptyState, Modal, Pagination, SearchInput, Select, Spinner } from '../components/UI';
import PatientForm from '../components/PatientForm';
import { listStudentFilters, listStudents } from '../services/emr';
import { ageFromBirthDate, formatDate } from '../utils/format';
import { useAuth } from '../context/AuthContext';

export default function PatientsPage(){
  const [params,setParams]=useState({page:1,pageSize:15,search:'',grade:'',section:'',sex:'',status:'',sort:'last_name',ascending:true});const [state,setState]=useState({loading:true,data:[],count:0});const [filters,setFilters]=useState({grades:[],sections:[]});const [edit,setEdit]=useState(null);const navigate=useNavigate();const {hasPermission}=useAuth();
  const load=()=>{setState(s=>({...s,loading:true}));listStudents(params).then(result=>setState({loading:false,...result})).catch(()=>setState({loading:false,data:[],count:0}));};
  useEffect(()=>{const id=setTimeout(load,params.search?350:0);return()=>clearTimeout(id);},[JSON.stringify(params)]);useEffect(()=>{listStudentFilters().then(setFilters).catch(()=>{});},[]);
  const set=(key,value)=>setParams(p=>({...p,[key]:value,page:1}));
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="page-title">Students and patients</h2><p className="muted mt-1">Search and manage authorized school clinic records.</p></div>{hasPermission('patients.create')&&<Button onClick={()=>setEdit({})}><Plus className="h-4 w-4"/>Register Patient</Button>}</div>
    <Card className="p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><SearchInput className="md:col-span-2" value={params.search} onChange={e=>set('search',e.target.value)} placeholder="Student ID, number, name, or contact…"/><Select label="Grade" value={params.grade} onChange={e=>set('grade',e.target.value)}><option value="">All grades</option>{filters.grades?.map(v=><option key={v}>{v}</option>)}</Select><Select label="Section" value={params.section} onChange={e=>set('section',e.target.value)}><option value="">All sections</option>{filters.sections?.map(v=><option key={v}>{v}</option>)}</Select><Select label="Sex" value={params.sex} onChange={e=>set('sex',e.target.value)}><option value="">All</option><option>Female</option><option>Male</option><option>Other</option></Select><Select label="Status" value={params.status} onChange={e=>set('status',e.target.value)}><option value="">All</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="GRADUATED">Graduated</option><option value="TRANSFERRED">Transferred</option></Select></div></Card>
    <Card className="overflow-hidden">{state.loading?<Spinner label="Searching patient records…"/>:state.data.length?<><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-900"><tr><th className="px-4 py-3">Student</th><th className="px-4 py-3">Grade / Section</th><th className="px-4 py-3">Age</th><th className="px-4 py-3">Sex</th><th className="px-4 py-3">Last Clinic Visit</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{state.data.map(row=><tr key={row.id} className="hover:bg-slate-50/70 dark:hover:bg-slate-800/40"><td className="px-4 py-3"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary-100 text-primary-600 dark:bg-primary-950"><UserRound className="h-5 w-5"/></div><div><button onClick={()=>navigate(`/patients/${row.id}`)} className="font-bold hover:text-primary-600">{row.full_name}</button><p className="text-xs text-slate-500">{row.student_id}{row.student_number?` · ${row.student_number}`:''}</p></div></div></td><td className="px-4 py-3">{row.grade_level} / {row.section}</td><td className="px-4 py-3">{ageFromBirthDate(row.birth_date)}</td><td className="px-4 py-3">{row.sex}</td><td className="px-4 py-3">{formatDate(row.last_visit)}</td><td className="px-4 py-3"><Badge tone={row.status==='ACTIVE'?'green':'slate'}>{row.status}</Badge></td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Button variant="ghost" size="sm" onClick={()=>navigate(`/patients/${row.id}`)} title="View"><Eye className="h-4 w-4"/></Button>{hasPermission('patients.update')&&<Button variant="ghost" size="sm" onClick={()=>setEdit(row)} title="Edit"><Pencil className="h-4 w-4"/></Button>}</div></td></tr>)}</tbody></table></div><Pagination page={params.page} pageSize={params.pageSize} total={state.count} onPage={page=>setParams(p=>({...p,page}))}/></>:<EmptyState title="No patients found" description="Try another search or register a new student patient." action={hasPermission('patients.create')?<Button onClick={()=>setEdit({})}>Register Patient</Button>:null}/>}</Card>
    <Modal open={edit!==null} onClose={()=>setEdit(null)} title={edit?.id?'Edit Patient':'Register Patient'} size="full"><PatientForm patient={edit?.id?edit:null} onCancel={()=>setEdit(null)} onSaved={id=>{setEdit(null);load();if(id)navigate(`/patients/${id}`);}}/></Modal>
  </div>;
}
