import { useEffect, useState } from 'react';
import { Button, Input, Select, Textarea } from './UI';
import { saveStudent } from '../services/emr';
import { useToast } from '../context/ToastContext';

const empty = {
  student_id:'',student_number:'',first_name:'',middle_name:'',last_name:'',suffix:'',birth_date:'',sex:'',grade_level:'',section:'',address:'',contact_number:'',email:'',status:'ACTIVE',
  guardian:{full_name:'',relationship:'',contact_number:'',email:'',address:''},
  medical:{blood_type:'',allergies:'',existing_conditions:'',current_medications:'',medical_history:'',immunization_information:'',medical_alerts:''}
};

export default function PatientForm({ patient, onSaved, onCancel }){
  const [form,setForm]=useState(empty);const [loading,setLoading]=useState(false);const [errors,setErrors]=useState({});const {toast}=useToast();
  useEffect(()=>{if(patient)setForm({...empty,...patient,guardian:{...empty.guardian,...(patient.guardian||{})},medical:{...empty.medical,...(patient.medical||{})}});},[patient]);
  const set=(key,value)=>setForm(current=>({...current,[key]:value}));
  const setNested=(group,key,value)=>setForm(current=>({...current,[group]:{...current[group],[key]:value}}));
  const submit=async e=>{e.preventDefault();const next={};['student_id','first_name','last_name','birth_date','sex','grade_level','section'].forEach(k=>{if(!form[k])next[k]='Required';});setErrors(next);if(Object.keys(next).length)return;setLoading(true);try{const id=await saveStudent({...form,id:patient?.id||form.id||null});toast(patient?'Patient updated successfully.':'Patient registered successfully.');onSaved?.(id);}catch(err){toast(err.message,'error');}finally{setLoading(false);}};
  return <form onSubmit={submit} className="space-y-7"><section><h3 className="mb-4 font-bold text-primary-700 dark:text-primary-300">Basic information</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Input label="Student ID" value={form.student_id} onChange={e=>set('student_id',e.target.value.toUpperCase())} error={errors.student_id} required/><Input label="Student Number" value={form.student_number||''} onChange={e=>set('student_number',e.target.value)}/><Input label="First Name" value={form.first_name} onChange={e=>set('first_name',e.target.value)} error={errors.first_name} required/><Input label="Middle Name" value={form.middle_name||''} onChange={e=>set('middle_name',e.target.value)}/><Input label="Last Name" value={form.last_name} onChange={e=>set('last_name',e.target.value)} error={errors.last_name} required/><Input label="Suffix" value={form.suffix||''} onChange={e=>set('suffix',e.target.value)}/><Input label="Birth Date" type="date" value={form.birth_date} onChange={e=>set('birth_date',e.target.value)} error={errors.birth_date} required/><Select label="Sex" value={form.sex} onChange={e=>set('sex',e.target.value)} error={errors.sex} required><option value="">Select</option><option>Female</option><option>Male</option><option>Other</option><option>Prefer not to say</option></Select><Select label="Status" value={form.status} onChange={e=>set('status',e.target.value)}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="GRADUATED">Graduated</option><option value="TRANSFERRED">Transferred</option></Select><Input label="Grade Level" value={form.grade_level} onChange={e=>set('grade_level',e.target.value)} error={errors.grade_level} required/><Input label="Section" value={form.section} onChange={e=>set('section',e.target.value)} error={errors.section} required/><Input label="Contact Number" value={form.contact_number||''} onChange={e=>set('contact_number',e.target.value)}/><Input label="Email" type="email" value={form.email||''} onChange={e=>set('email',e.target.value)} /><div className="sm:col-span-2 lg:col-span-3"><Textarea label="Address" value={form.address||''} onChange={e=>set('address',e.target.value)} /></div></div></section>
    <section><h3 className="mb-4 font-bold text-primary-700 dark:text-primary-300">Parent / guardian and emergency contact</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Input label="Full Name" value={form.guardian.full_name} onChange={e=>setNested('guardian','full_name',e.target.value)}/><Input label="Relationship" value={form.guardian.relationship} onChange={e=>setNested('guardian','relationship',e.target.value)}/><Input label="Contact Number" value={form.guardian.contact_number} onChange={e=>setNested('guardian','contact_number',e.target.value)}/><Input label="Email" type="email" value={form.guardian.email} onChange={e=>setNested('guardian','email',e.target.value)}/><div className="sm:col-span-2"><Input label="Address" value={form.guardian.address} onChange={e=>setNested('guardian','address',e.target.value)}/></div></div></section>
    <section><h3 className="mb-4 font-bold text-primary-700 dark:text-primary-300">Medical information</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Select label="Blood Type" value={form.medical.blood_type} onChange={e=>setNested('medical','blood_type',e.target.value)}><option value="">Unknown</option>{['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(v=><option key={v}>{v}</option>)}</Select><Input label="Allergies" value={form.medical.allergies} onChange={e=>setNested('medical','allergies',e.target.value)}/><Input label="Existing Conditions" value={form.medical.existing_conditions} onChange={e=>setNested('medical','existing_conditions',e.target.value)}/><Input label="Current Medications" value={form.medical.current_medications} onChange={e=>setNested('medical','current_medications',e.target.value)}/><div className="sm:col-span-2"><Input label="Immunization Information" value={form.medical.immunization_information} onChange={e=>setNested('medical','immunization_information',e.target.value)}/></div><div className="sm:col-span-2 lg:col-span-3"><Textarea label="Medical History" value={form.medical.medical_history} onChange={e=>setNested('medical','medical_history',e.target.value)}/></div><div className="sm:col-span-2 lg:col-span-3"><Textarea label="Important Medical Alerts" value={form.medical.medical_alerts} onChange={e=>setNested('medical','medical_alerts',e.target.value)}/></div></div></section>
    <div className="flex justify-end gap-2"><Button variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" loading={loading}>{patient?'Save Changes':'Register Patient'}</Button></div></form>;
}
