import { useEffect, useState } from 'react';
import { Check, Search, UserRound, X } from 'lucide-react';
import { listStudents } from '../services/emr';
import { Spinner } from './UI';

export default function StudentPicker({ value, onChange, initialStudent = null, label = 'Patient', required = false }) {
  const [search,setSearch]=useState('');const [results,setResults]=useState([]);const [loading,setLoading]=useState(false);const [open,setOpen]=useState(false);const [selected,setSelected]=useState(initialStudent);
  useEffect(()=>{if(initialStudent)setSelected(initialStudent);},[initialStudent]);
  useEffect(()=>{if(!open||search.trim().length<1)return;const timer=setTimeout(async()=>{setLoading(true);try{const r=await listStudents({search,pageSize:8,status:'ACTIVE'});setResults(r.data);}finally{setLoading(false);}},300);return()=>clearTimeout(timer);},[search,open]);
  const choose=row=>{setSelected(row);onChange?.(row.id,row);setSearch('');setOpen(false);};
  const clear=()=>{setSelected(null);onChange?.('',null);setOpen(true);};
  return <div className="relative"><span className="form-label">{label}{required&&<span className="ml-1 text-red-500">*</span>}</span>{selected?<div className="flex items-center gap-3 rounded-xl border border-primary-200 bg-primary-50 p-3 dark:border-primary-900 dark:bg-primary-950/35"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary-100 text-primary-600 dark:bg-primary-900"><UserRound className="h-5 w-5"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{selected.full_name}</p><p className="text-xs text-slate-500">{selected.student_id} · {selected.grade_level} / {selected.section}</p></div><button type="button" onClick={clear} className="rounded-lg p-2 hover:bg-primary-100 dark:hover:bg-primary-900" aria-label="Clear patient"><X className="h-4 w-4"/></button></div>:<div className="relative"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>{setSearch(e.target.value);setOpen(true);}} onFocus={()=>setOpen(true)} className="input-base pl-10" placeholder="Search student ID or name…" required={required}/>{open&&search&&<div className="absolute z-30 mt-2 max-h-72 w-full overflow-y-auto rounded-xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-slate-900">{loading?<div className="p-3"><Spinner label="Searching…"/></div>:results.length?results.map(row=><button type="button" key={row.id} onClick={()=>choose(row)} className="flex w-full items-center gap-3 border-b border-slate-100 p-3 text-left hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-800"><UserRound className="h-5 w-5 text-primary-500"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{row.full_name}</p><p className="text-xs text-slate-500">{row.student_id} · {row.grade_level} / {row.section}</p></div><Check className="h-4 w-4 text-slate-300"/></button>):<p className="p-5 text-center text-sm text-slate-500">No matching active students.</p>}</div>}</div>}</div>;
}
